### PR TITLE
Add fixed issues on contact form

### PR DESCRIPTION
**Pull request by ecekpo**
Add fixed issues with contact form validation

### CODE REVIEW

**Review by omarsalem7 — CHANGES_REQUESTED** [review]
Hi @ecekpo , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

Almost near

 ## Highlights
✔️ All linter checks pass
✔️ Descriptive pull request

 ## Required Changes ♻️

- [ ] Please add changes which requested by previous reviewer in this [pull request](https://github.com/ecekpo/Portfolio/pull/12) and in the next time please don't open a new pull request for requested changes use the same request, you can continue in this PR but made changes in the previous PR.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ecekpo** [comment]
Hello Omarsalem,
I mistakenly use a wrong branch which did not carry my main information I last worked with. As soon as I noticed this, I went to the dashboard and removed the submitted work for review not knowing that it has reach your end. 
Please, this is the right branch and kindly ignored the first one sent by error.
Thanks for your understanding.

Emem Ekpo (she/her)    On Friday, June 24, 2022 at 11:56:43 AM GMT+1, Omar Salem ***@***.***> wrote:  
 
 


@omarsalem7 requested changes on this pull request.

Hi @ecekpo ,

Great work on making the changes requested by a previous reviewer 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.



Highlights

 ✔️ All linter checks pass
 ✔️ Descriptive pull request

Required Changes ♻️
    
   -  Please add changes which requested by previous reviewer in this pull request and in the next time please don't open a new pull request for requested changes use the same request, you can continue in this PR but made changes in the previous PR.

Cheers and Happy coding! 👏 👏 👏
 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the Code reviews limits policy you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this form.

**Review by roshan-bajgain — CHANGES_REQUESTED** [review]
Hi @ecekpo, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️
- PR has a good title and summary. ✔️

 ## Required Changes ♻️

- [ ] Kindly make changes requested by the previous reviewer.
- [ ] If a user submits the contact form with the email field containing uppercase characters an error message should show up near the submit button. Kindly implement it as it is not working on your project

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by bimbolabuari — COMMENTED** [review]
Hello @ecekpo 👋,

_This is an additional review as a result of the second opinion request._

Great work on this milestone so far. 👍🏽

Although you have implemented your Javascript in your previous milestone, As requested by the previous CRs, the form validation throws an error, so when I try to submit an invalid email, it throws an error. Kindly fix this

Screenshot (573)


Keep rocking 🚀!

**Review by bimbolabuari — COMMENTED** [review]
Hello @ecekpo 👋 

Great work on making the changes requested by a previous reviewer 👏 

You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Required Changes ♻️
- While you have been able to display the form validation message, I suggest you create an element that shows the message instead of changing the button innerHTML so that the button still remains visible.

Happy coding 🚀 !

**Comment by ecekpo** [comment]
Hello Abimbola,
Good morning.
Kindly find the link regarding the changes for the PR Add fixed issues on contact form by ecekpo · Pull Request #13 · ecekpo/Portfolio

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Add fixed issues on contact form by ecekpo · Pull Request #13 · ecekpo/P...

Add fixed issues with contact form validation
 |

 |

 |


Thank you.
Emem Ekpo (she/her)

    On Saturday, June 25, 2022 at 12:13:38 AM GMT+1, Abimbola Buari ***@***.***> wrote:  
 
 


@bimbolabuari commented on this pull request.

Hello @ecekpo 👋
 
Great work on making the changes requested by a previous reviewer 👏
 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

Required Changes ♻️
    
   - While you have been able to display the form validation message, I suggest you create an element that shows the message instead of changing the button innerHTML so that the button still remains visible.

Happy coding 🚀 !

**Review by bimbolabuari — APPROVED** [review]
Hi @ecekpo 👋 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
